CREATE DATABASE Blogsphere CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE Blogsphere;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  NOM VARCHAR(100) UNIQUE NOT NULL,
  bio TEXT,
  avatar VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

